# -*- coding: utf-8 -*-
from setuptools import setup, find_packages


setup(
    name='doorman',
    description='an osquery fleet manager',
    url='https://github.com/mwielgoszewski/doorman',
    version='0.5.1',
    packages=find_packages(
        exclude=[
            'tests*',
        ]
    ),
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        'alembic',
        'amqp',
        'anyjson',
        'bcrypt',
        'billiard',
        'blinker',
        'celery',
        'cffi',
        'contextlib2',
        'cssmin',
        'enum34',
        'Flask',
        'Flask-Assets',
        'Flask-Bcrypt',
        'Flask-DebugToolbar',
        'flask-ldap3-login',
        'Flask-Login',
        'Flask-Mail',
        'Flask-Migrate',
        'flask-paginate',
        'Flask-Script',
        'Flask-SQLAlchemy',
        'Flask-WTF',
        'itsdangerous',
        'Jinja2',
        'jsmin',
        'kombu',
        'ldap3',
        'Mako',
        'MarkupSafe',
        'oauthlib',
        'psycopg2',
        'pyasn1',
        'pycparser',
        'python-editor',
        'pytz',
        'raven',
        'redis',
        'requests',
        'requests-oauthlib',
        'scales',
        'SQLAlchemy',
        'webassets',
        'Werkzeug',
        'WTForms',
    ],
    package_data={
        'resources': 'doorman/resources/*',
        'static': 'doorman/static/*',
        'templates': 'doorman/templates/*',
    }
)
